services:
  backend_rds:
    image: 148761653308.dkr.ecr.eu-north-1.amazonaws.com/backend_rds:5fc614d
    ports:
      - "8001:8001"
    networks:
      - my_network
    environment:
      - DB_HOST=mydatabase.ctokg0ogebib.eu-north-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=mypostgres
      - DB_PASSWORD=mypassword1
      - CORS_ALLOWED_ORIGINS

  backend_redis:
    image: 148761653308.dkr.ecr.eu-north-1.amazonaws.com/backend_redis:5fc614d
    ports:
      - "8002:8002"
    networks:
      - my_network
    environment:
      - REDIS_HOST=redis1.x6wn37.ng.0001.eun1.cache.amazonaws.com
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword1mypassword1
      - REDIS_DB=0
      - CORS_ALLOWED_ORIGINS

networks:
  my_network:
    driver: bridge