name: Frontend Push and Deploy

on:
  push:
    paths:
      - 'frontend/**'
      - 'terraform/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker image version
        id: version
        run: |
          VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build \
            -t my-demo-frontend:$IMAGE_VERSION \
            --build-arg VERSION=$IMAGE_VERSION \
            ./frontend

      - name: Tag and push Docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/frontend:$IMAGE_VERSION
          docker tag my-demo-frontend:$IMAGE_VERSION $IMAGE_URI
          docker push $IMAGE_URI

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ vars.CLUSTER_NAME}} \
            --service frontend-service \
            --force-new-deployment
