name: Terraform CI/CD

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download terraform.tfvars artifact (if exists)
        uses: actions/download-artifact@v3
        with:
          name: terraform-vars
          path: .
        continue-on-error: true  # Якщо артефакт відсутній, пайплайн не має падати

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Check Terraform formatting
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config="key=terraform.tfstate"

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan || terraform plan -out=tfplan  # Якщо tfvars немає, просто план без нього

      - name: Terraform Apply
        if: github.ref_name == 'main'
        run: terraform apply -auto-approve tfplan
