name: Terraform CI/CD

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend.tfvars artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: frontend-vars
          path: ./
        continue-on-error: true

      - name: Download backend_rds.tfvars artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: backend-rds-vars
          path: ./
        continue-on-error: true

      - name: Download backend_redis.tfvars artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: backend-redis-vars
          path: ./
        continue-on-error: true

      - name: Combine tfvars files
        run: |
          # Створюємо єдиний terraform.tfvars файл з усіх окремих
          cat frontend.tfvars backend_rds.tfvars backend_redis.tfvars > terraform.tfvars 2>/dev/null || true
          
          # Якщо файл порожній, додаємо базові значення
          if [ ! -s terraform.tfvars ]; then
            echo "# Default values" > terraform.tfvars
            echo "frontend_image_tag = \"latest\"" >> terraform.tfvars
            echo "backend_rds_image_tag = \"latest\"" >> terraform.tfvars
            echo "backend_redis_image_tag = \"latest\"" >> terraform.tfvars
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Check Terraform formatting
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config="key=terraform.tfstate"

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        if: github.ref_name == 'main'
        run: terraform apply -auto-approve tfplan